# Generated by Django 5.2.15 on 2026-07-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
