# Generated by Django 5.2.15 on 2026-07-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_communicationlog_last_retry_at_and_more'),
        ('customers', '0001_initial'),
        ('tenancy', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationautomation',
            name='delay_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communicationautomation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='communicationautomation',
            name='last_executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationautomation',
            name='last_execution_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='communicationautomation',
            name='max_retry_attempts',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='communicationqueue',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='communicationqueue',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationqueue',
            name='rendered_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='communicationqueue',
            name='rendered_subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='communicationqueue',
            index=models.Index(fields=['organization', 'status'], name='comm_queue_status_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationqueue',
            index=models.Index(fields=['organization', 'scheduled_at'], name='comm_queue_schedule_idx'),
        ),
    ]
