# Generated by Django 5.2.15 on 2026-07-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_alter_communicationqueue_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
