# Generated by Django 5.2.17 on 2026-09-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_alter_communicationlog_status'),
        ('customers', '0004_notificationpreference_email_enabled_and_more'),
        ('tenancy', '0004_staffprofile'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='communicationqueue',
            index=models.Index(fields=['status', 'scheduled_at', 'priority', 'created_at'], name='comm_q_sched_prio_idx'),
        ),
    ]
