# Generated by Django 5.2.17 on 2026-09-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoice_cancellation_reason_invoice_cancelled_at_and_more'),
        ('customers', '0004_notificationpreference_email_enabled_and_more'),
        ('tenancy', '0004_staffprofile'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'service_account', 'billing_period_start', 'billing_period_end'], name='inv_org_svc_period_idx'),
        ),
    ]
