# Generated by Django 5.2.17 on 2026-09-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(choices=[('MANUAL', 'Manual Journal Entry'), ('INVOICE', 'Customer Invoice'), ('PAYMENT', 'Customer Payment'), ('PAYMENT_REVERSAL', 'Payment Reversal'), ('INVOICE_CANCEL', 'Invoice Cancellation'), ('EXPENSE', 'Operational Expense'), ('INCOME', 'Direct Income'), ('TRANSFER', 'Cash / Bank Transfer'), ('DEALER_ACCRUAL', 'Dealer Commission Accrual'), ('DEALER_SETTLEMENT', 'Dealer Payout Settlement'), ('POS_SALE', 'POS Hardware Sale'), ('POS_SALE_REVERSAL', 'POS Sale Cancellation Reversal')], default='MANUAL', max_length=40),
        ),
    ]
