# Generated by Django 5.2.17 on 2026-09-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_journalentry_reference_type'),
        ('tenancy', '0004_staffprofile'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account', 'created_at'], name='jline_acct_created_idx'),
        ),
    ]
