# Generated by Django 5.2.15 on 2026-07-05 09:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('tenancy', '0002_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('node_type', models.CharField(choices=[('ROUTER', 'Router'), ('OLT', 'OLT'), ('SWITCH', 'Switch'), ('ACCESS_POINT', 'Access Point'), ('OTHER', 'Other')], max_length=30)),
                ('management_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenancy.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenancy.organization')),
                ('service_account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='network_assignment', to='customers.serviceaccount')),
                ('network_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_assignments', to='network.networknode')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ProvisioningRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ACTIVATE', 'Activate'), ('SUSPEND', 'Suspend'), ('RESTORE', 'Restore'), ('CHANGE_PACKAGE', 'Change Package')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('requested_payload', models.JSONField(blank=True, default=dict)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provisioning_requests', to='network.networkassignment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenancy.organization')),
                ('service_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provisioning_requests', to='customers.serviceaccount')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='networknode',
            index=models.Index(fields=['organization', 'is_active'], name='network_node_org_active_idx'),
        ),
        migrations.AddIndex(
            model_name='networknode',
            index=models.Index(fields=['organization', 'node_type'], name='network_node_org_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='networknode',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_network_node_code_per_org'),
        ),
        migrations.AddIndex(
            model_name='networkassignment',
            index=models.Index(fields=['organization', 'is_active'], name='network_assign_org_active_idx'),
        ),
        migrations.AddIndex(
            model_name='networkassignment',
            index=models.Index(fields=['organization', 'network_node'], name='network_assign_org_node_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioningrequest',
            index=models.Index(fields=['organization', 'status'], name='provision_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioningrequest',
            index=models.Index(fields=['organization', 'action'], name='provision_org_action_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioningrequest',
            index=models.Index(fields=['organization', 'service_account'], name='provision_org_service_idx'),
        ),
        migrations.AddConstraint(
            model_name='provisioningrequest',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='unique_provisioning_idempotency_per_org'),
        ),
    ]
